# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LSzYTm8yzX8orNVIC_bEUjUZZvOnuHgP
"""

import os

import tensorflow as tf
import tensorflow_hub as hub
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import re
import seaborn as sns

module_url = "https://tfhub.dev/google/universal-sentence-encoder/2" #@param ["https://tfhub.dev/google/universal-sentence-encoder/2", "https://tfhub.dev/google/universal-sentence-encoder-large/3"]

embed = hub.Module(module_url)

os.getcwd()

from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)

root_path = 'gdrive/My Drive/Colab Notebooks/'

from google.colab import drive

drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/your_project_folder/'

!ls

!mkdir input  #create a directory named test/
!unzip -q sample_input.zip -d input/  #unzip data in train/

fn = "sample_input.txt"
fi = open("sample_input.txt", 'r')
text = fi.read()

paragraph=[]
with open("sample_input.txt",'r') as fi:
  for line in fi:
    paragraph.append(line)

messages = paragraph

with tf.Session() as session:
  session.run([tf.global_variables_initializer(), tf.tables_initializer()])
  message_embeddings = session.run(embed(messages))

  for i, message_embedding in enumerate(np.array(message_embeddings).tolist()):
    print("Message: {}".format(messages[i]))
    print("Embedding size: {}".format(len(message_embedding)))
    message_embedding_snippet = ", ".join(
        (str(x) for x in message_embedding[:3]))
    print("Embedding: [{}, ...]\n".format(message_embedding_snippet))